### ISSUE TITLE
P004207 wrong colour when scatterplot is downloaded

### ISSUE THREAD

**Issue by pajuyah** [CCI-BIO/ZERO_Viewer#1]
Hi

My zeroviewer is colouring my patient (red) differently from after it is downloaded (green). Please see copied screenshot. Could I have it the same please, cheers. @njayatilleke @poojavenkat @cmayoh 

![image](https://user-images.githubusercontent.com/69130357/89139489-26b3be00-d582-11ea-9121-16646db1cd7c.png)

**Comment by poojavenkat** [comment]
> Hi
> 
> My zeroviewer is colouring my patient (red) differently from after it is downloaded (green). Please see copied screenshot. Could I have it the same please, cheers. @njayatilleke @poojavenkat @cmayoh
> 
> ![image](https://user-images.githubusercontent.com/69130357/89139489-26b3be00-d582-11ea-9121-16646db1cd7c.png)

Hi @pajuyah , 

Currently working on your issue. Will get back to you soon.

**Comment by poojavenkat** [comment]
The new release v1.0.3. solves this issue.
