### ISSUE TITLE
Problems with zeroviewer

### ISSUE THREAD

**Issue by pajuyah** [CCI-BIO/ZERO_Viewer#2]
Hi,

I am having issues opening zeroviewer. Please see the screenshots.

![Capture](https://user-images.githubusercontent.com/69130357/100675127-74b6c200-33ba-11eb-8ae5-bf252eb4c5a6.JPG)
![image](https://user-images.githubusercontent.com/69130357/100675150-85ffce80-33ba-11eb-8463-b738d93404ea.png)

@njayatilleke @poojavenkat @cmayoh

**Comment by njayatilleke** [comment]
Hi,

I will get in touch with you via email regarding this issue. It is likely that we will need to do a reinstall on your computer. 

Cheers
